#!/bin/bash
echo "Pi in the Sky - Installation"
echo "============================"

rev=$(cat /proc/cpuinfo|grep Revision|awk -F: '$0=$2'|tr -d ' ' )
echo $rev

case "$rev" in
        a21041)
            echo "Pi 2B Detected"
            ;;
        *)
            echo $"Something else"
            exit 1


esac








sudo raspi-config nonint do_spi 0 #Lora board only
sudo raspi-config nonint do_i2c 0 #default or only for BMP085/180
sudo raspi-config nonint do_onewire 0 #Default

sudo apt-get update && apt-get install git

sudo raspi-config nonint do_camera 0



sudo systemctl mask serial-getty@ttyAMA0.service
#sudo nano /boot/cmdline.txt remove the part that says console=serial0,115200

#sudo nano /boot/config.txt
#then go to the end of the file and add a new line containing this:
#dtoverlay=pi3-disable-bt
sudo systemctl disable hciuart


echo "Installing PiGPIO"
echo "================="
sleep 3

cd
wget abyz.co.uk/rpi/pigpio/pigpio.zip
unzip pigpio.zip
cd PIGPIO
make
sudo make install

echo "Installing Wiring Pi"
echo "===================="
sleep 3
cd
git clone git://git.drogon.net/wiringPi
cd wiringPi
./build

echo "Installing SSDV"
echo "==============="
sleep 3
cd
git clone https://github.com/fsphil/ssdv.git
cd ssdv
sudo make install

echo "Installing fswebcam"
echo "==================="
sleep 3
sudo apt-get install fswebcam


echo "Installing Pi in the Sky Software"
echo "================================="

cd
git clone https://github.com/PiInTheSky/pits.git
cd pits
./build






