#!/bin/bash
echo Camera script ...

cd /home/pi/pits/tracker
mkdir -p keep


while [ 1 ]
do

	echo Taking photo for SSDV
	if [ -e take_pic ]
	then
		# i=$[i+1]
		current_time=$(date "+%H_%M_%S")
		./take_pic $current_time
	fi

	echo sleeping ...
	sleep 15

	echo Taking photo for storage
	current_date=$(date "+%d_%m_%y")
	current_time=$(date "+%H_%M_%S")
	mkdir -p keep/$current_date
	raspistill -w 2592 -h 1944 -v -t 3000 -ex auto -mm matrix -o keep/$current_date/$current_time.jpg

	echo sleeping ...
	sleep 15
done
