#!/bin/bash
cd /home/pi/tracker
echo Camera script ...

rm take_pic

i=0
while [ 1 ]
do
	i=$[i+1]

	echo Taking photo for SSDV
	./take_pic ${i}

	sleep 15

	echo Taking photo for storage
    raspistill -w 2592 -h 1944 -v -t 1000 -ex auto -mm matrix -o /home/pi/tracker/keep/flight$1.jpg

    sleep 15
done
