#!/bin/bash
cd /home/pi/pits/tracker
sudo ./camera &
# sleep 30
# sudo python3 gopro.py &
# python3 sensors.py &
# python3 astro_led.py &
# python3 webstuff.py
# sudo python3 gopro.py &
while :
do
	sudo ./tracker
	sleep 5
done

